23.1. Reliably Load External JS with Stimulus
  Thanks to the turbo-frame system, we're now lazily-loading just part of the weather page down in the footer. And... notice that this is working... which actually proves something: script tags inside frames are executed.

  script Tags in Frames Are Executed
  - Let me find that frame... here it is. Ok, so no surprise: if you have a <script> tag that's included in a turbo-frame, Turbo does execute that... exactly like how Turbo Drive executes any script tags found inside the body element.

  That's great! But... we have a bug that's hiding. Well, sort of two bugs. Yikes! To see the first, scroll to the top of the page, refresh but don't scroll down. Now click to the weather page... and check out the console. Error!

    Uncaught reference error: __weatherwidget_init() is not a function

  And it's coming from turbo-helper. Go open that file - turbo/turbo-helper.js and scroll down to line 71. Here we are: initializeWeatherWidget().

  If you scroll back up, this initializeWeatherWidget() function is called when the turbo:render event is dispatched. Its job is to reinitialize the weather widget on the next page. The problem is that, in this case, the weather widget JavaScript hasn't quite yet been loaded onto the page... because it didn't load at all on the first page. And the real problem is that... well... I didn't code defensively.

  Fix this by adding an if: if typeof __weatherwidget_init === 'function', then call this. Otherwise, it means the JavaScript hasn't been loaded... so no reason to do anything.